# Generated by Django 5.0.3 on 2024-05-06 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_depart', models.CharField(max_length=255)),
                ('depart', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nom_arrivee', models.CharField(max_length=255)),
                ('arrivee', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('itineraire', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('presentation', models.TextField()),
            ],
        ),
    ]
