# Generated by Django 5.0.3 on 2024-06-05 17:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursDeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('nomentiteh', models.CharField(max_length=255)),
                ('candidat', models.CharField(max_length=255)),
                ('classe', models.IntegerField()),
                ('layer', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Glossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255)),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Glossaire',
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itineraire', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('scenario', models.TextField()),
                ('commentaire', models.TextField(help_text="Commentaire sur l'itinéraire", null=True)),
            ],
            options={
                'verbose_name_plural': 'Itinéraires',
            },
        ),
        migrations.CreateModel(
            name='ItineraireDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'itineraire/glossaire',
            },
        ),
        migrations.CreateModel(
            name='LienRenumar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField()),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LienRenumarItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LienRenumarPointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('cdentitehy', models.CharField(max_length=255)),
                ('nomentiteh', models.CharField(max_length=255)),
                ('candidat', models.CharField(max_length=255, null=True)),
                ('classe', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Materiaux',
            },
        ),
        migrations.CreateModel(
            name='MateriauxDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(help_text="Ajouter si l'information est disponible la quantité et la valeur", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriauxDansPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'point/materiaux',
                'verbose_name_plural': 'points/materiaux',
            },
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Metiers',
            },
        ),
        migrations.CreateModel(
            name='MetierDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'metier/glossaire',
            },
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personnages',
            },
        ),
        migrations.CreateModel(
            name='PersonnageDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PointDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'point/glossaire',
            },
        ),
        migrations.CreateModel(
            name='PointDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionDansItineraire', models.IntegerField()),
            ],
            options={
                'ordering': ['positionDansItineraire'],
            },
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom unique du point d'intérêt", max_length=255, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('presentation', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Points d'intérêt",
            },
        ),
        migrations.CreateModel(
            name='TypePointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': "Types de point d'intérêt",
            },
        ),
        migrations.AddConstraint(
            model_name='glossaire',
            constraint=models.UniqueConstraint(fields=('mot',), name='unique_motGlossaire'),
        ),
        migrations.AddField(
            model_name='itinerairedansglossaire',
            name='fk_glossaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire'),
        ),
        migrations.AddField(
            model_name='itinerairedansglossaire',
            name='fk_itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire'),
        ),
        migrations.AddField(
            model_name='lienrenumaritineraire',
            name='itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire'),
        ),
        migrations.AddField(
            model_name='lienrenumaritineraire',
            name='lien_renumar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.lienrenumar'),
        ),
        migrations.AddField(
            model_name='lienrenumarpointinteret',
            name='lien_renumar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.lienrenumar'),
        ),
        migrations.AddField(
            model_name='materiauxdansitineraire',
            name='fk_itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire'),
        ),
        migrations.AddField(
            model_name='materiauxdansitineraire',
            name='fk_materiaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.materiaux'),
        ),
        migrations.AddField(
            model_name='materiauxdanspoint',
            name='fk_materiaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.materiaux'),
        ),
        migrations.AddField(
            model_name='metierdansglossaire',
            name='fk_glossaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire'),
        ),
        migrations.AddField(
            model_name='metierdansglossaire',
            name='fk_metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.metier'),
        ),
        migrations.AddField(
            model_name='personnage',
            name='metiers_personnage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.metier'),
        ),
        migrations.AddField(
            model_name='personnagedansitineraire',
            name='fk_itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire'),
        ),
        migrations.AddField(
            model_name='personnagedansitineraire',
            name='fk_personnage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.personnage'),
        ),
        migrations.AddField(
            model_name='pointdansglossaire',
            name='fk_glossaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire'),
        ),
        migrations.AddField(
            model_name='pointdansitineraire',
            name='fk_itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='map.itineraire'),
        ),
        migrations.AddField(
            model_name='pointdansitineraire',
            name='fk_pointInteret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret'),
        ),
        migrations.AddField(
            model_name='pointdansglossaire',
            name='fk_pointInteret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret'),
        ),
        migrations.AddField(
            model_name='materiauxdanspoint',
            name='fk_pointInteret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret'),
        ),
        migrations.AddField(
            model_name='lienrenumarpointinteret',
            name='point_interet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='arrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivee_itineraires', to='map.pointinteret'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart_itineraires', to='map.pointinteret'),
        ),
        migrations.AddConstraint(
            model_name='typepointinteret',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_typePoint'),
        ),
        migrations.AddField(
            model_name='pointinteret',
            name='type_point_interet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.typepointinteret'),
        ),
        migrations.AddConstraint(
            model_name='itinerairedansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_itineraire', 'fk_glossaire'), name='unique_itineraireDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='metierdansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_metier', 'fk_glossaire'), name='unique_metierDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='personnage',
            constraint=models.UniqueConstraint(fields=('prenom', 'nom'), name='unique_nomPrenom'),
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_itineraire'), name='unique_pointDansItineraire'),
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_itineraire', 'positionDansItineraire'), name='unique_positionDansItineraire'),
        ),
        migrations.AddConstraint(
            model_name='pointdansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_glossaire'), name='unique_pointDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='materiauxdanspoint',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_materiaux'), name='unique_materiauxDansPoint'),
        ),
    ]
