# Generated by Django 5.0.3 on 2024-05-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='arrivee',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='depart',
        ),
    ]
