# Generated by Django 5.0.3 on 2024-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loiremodel',
            name='cdentitehy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loiremodel',
            name='nomentiteh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
