# Generated by Django 5.0.3 on 2024-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_itineraire_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='commentaire',
            field=models.TextField(help_text="Commentaire sur l'itinéraire", null=True),
        ),
    ]
