# Generated by Django 5.0.3 on 2024-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_loiremodel_cdentitehy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursdeau',
            name='cdentitehy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursdeau',
            name='candidat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursdeau',
            name='layer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursdeau',
            name='nomentiteh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursdeau',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
