# Generated by Django 5.0.3 on 2024-05-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_itineraire_arrivee_remove_itineraire_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pointinteret',
            name='type_point_interet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.typepointinteret'),
        ),
    ]
