# Generated by Django 5.0.6 on 2024-05-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_itineraire_commentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lienrenumaritineraire',
            options={'verbose_name': 'Lien Renumar/Itinéraire'},
        ),
        migrations.AlterModelOptions(
            name='lienrenumarpointinteret',
            options={'verbose_name': "Lien Renumar/Point d'Intérêt"},
        ),
        migrations.AddField(
            model_name='lienrenumar',
            name='titre',
            field=models.CharField(default='lien renumar', max_length=255),
        ),
        migrations.AlterField(
            model_name='glossaire',
            name='mot',
            field=models.CharField(help_text="Ajoutez ce mot uniquement s'il appartient à la présentation d'un point d'intérêt.", max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerairedansglossaire',
            name='fk_glossaire',
            field=models.ForeignKey(help_text="Ajoutez ce mot uniquement s'il appartient à la description de l'itinéraire sélectionné.", on_delete=django.db.models.deletion.CASCADE, to='map.glossaire'),
        ),
        migrations.AlterField(
            model_name='itinerairedansglossaire',
            name='fk_itineraire',
            field=models.ForeignKey(help_text="Sélectionnez l'itinéraire correspondant.", on_delete=django.db.models.deletion.CASCADE, to='map.itineraire'),
        ),
        migrations.AlterField(
            model_name='lienrenumar',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lienrenumaritineraire',
            name='lien_renumar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.lienrenumar'),
        ),
        migrations.AlterField(
            model_name='lienrenumarpointinteret',
            name='lien_renumar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.lienrenumar'),
        ),
        migrations.AlterField(
            model_name='pointdansglossaire',
            name='fk_glossaire',
            field=models.ForeignKey(help_text="Ajoutez ce mot uniquement s'il appartient à la présentation du point d'intérêt sélectionné.", on_delete=django.db.models.deletion.CASCADE, to='map.glossaire'),
        ),
        migrations.AlterField(
            model_name='pointdansglossaire',
            name='fk_pointInteret',
            field=models.ForeignKey(help_text="Sélectionnez le point d'intérêt correspondant.", on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret'),
        ),
        migrations.AlterField(
            model_name='typepointinteret',
            name='description',
            field=models.TextField(default='description du type', help_text='Ajouter une description.'),
        ),
        migrations.AddConstraint(
            model_name='lienrenumaritineraire',
            constraint=models.UniqueConstraint(fields=('itineraire', 'lien_renumar'), name='unique_lien_renumar_itineraire'),
        ),
        migrations.AddConstraint(
            model_name='lienrenumarpointinteret',
            constraint=models.UniqueConstraint(fields=('point_interet', 'lien_renumar'), name='unique_lien_renumar_point_interet'),
        ),
    ]
