# Generated by Django 5.0.3 on 2024-05-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_typepointinteret_pointinteret_type_point_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=255)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuantite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(verbose_name=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(verbose_name=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pointinteret',
            name='materiaux',
            field=models.ManyToManyField(to='map.materiaux'),
        ),
        migrations.CreateModel(
            name='Personnages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('metiers_personnage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.metiers')),
            ],
        ),
    ]
