# Generated by Django 5.0.3 on 2024-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_itineraire_arrivee_itineraire_depart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointdansitineraire',
            name='unique_positionDansItineraire',
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_itineraire', 'positionDansItineraire', 'fk_pointInteret'), name='unique_positionDansItineraire'),
        ),
    ]
