# Generated by Django 5.0.6 on 2024-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_lienrenumaritineraire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Commentaire sur l'itinéraire", null=True),
        ),
    ]
