# Generated by Django 5.0.6 on 2024-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_itineraire_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienrenumar',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiauxdansitineraire',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Ajouter si l'information est disponible la quantité et la valeur", null=True),
        ),
        migrations.AlterField(
            model_name='metier',
            name='description',
            field=models.TextField(help_text='Description du métier', null=True),
        ),
    ]
