# Generated by Django 5.0.3 on 2024-05-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_metiers_metier_rename_personnages_personnage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaire',
            options={'verbose_name_plural': 'Glossaire'},
        ),
        migrations.AlterModelOptions(
            name='itineraire',
            options={'verbose_name_plural': 'Itineraires'},
        ),
        migrations.AlterModelOptions(
            name='materiaux',
            options={'verbose_name_plural': 'Materiaux'},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'verbose_name_plural': 'Metiers'},
        ),
        migrations.AlterModelOptions(
            name='personnage',
            options={'verbose_name_plural': 'Personnages'},
        ),
        migrations.AlterModelOptions(
            name='pointinteret',
            options={'verbose_name_plural': "Points d'intérêt"},
        ),
        migrations.AlterModelOptions(
            name='typepointinteret',
            options={'verbose_name_plural': "Types de point d'intérêt"},
        ),
        migrations.AlterModelOptions(
            name='typequantite',
            options={'verbose_name_plural': 'Types de quantité'},
        ),
        migrations.AlterModelOptions(
            name='typevaleur',
            options={'verbose_name_plural': 'Types de valeur'},
        ),
        migrations.RemoveField(
            model_name='pointinteret',
            name='materiaux',
        ),
        migrations.AlterField(
            model_name='typequantite',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typevaleur',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ItineraireDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_glossaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire')),
                ('fk_itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire')),
            ],
            options={
                'verbose_name': 'itineraire/glossaire',
            },
        ),
        migrations.CreateModel(
            name='MateriauxDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('valeur', models.FloatField()),
                ('fk_itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire')),
                ('fk_materiaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.materiaux')),
                ('fk_typeQuantité', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.typequantite')),
                ('fk_typeValeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.typevaleur')),
            ],
        ),
        migrations.CreateModel(
            name='MateriauxDansPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_materiaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.materiaux')),
                ('fk_pointInteret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret')),
            ],
            options={
                'verbose_name': 'point/materiaux',
                'verbose_name_plural': 'points/materiaux',
            },
        ),
        migrations.CreateModel(
            name='MetierDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_glossaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire')),
                ('fk_metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.metier')),
            ],
            options={
                'verbose_name': 'metier/glossaire',
            },
        ),
        migrations.CreateModel(
            name='PointDansGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_glossaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.glossaire')),
                ('fk_pointInteret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret')),
            ],
            options={
                'verbose_name': 'point/glossaire',
            },
        ),
        migrations.CreateModel(
            name='PointDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionDansItineraire', models.IntegerField()),
                ('fk_itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire')),
                ('fk_pointInteret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itinerairedansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_itineraire', 'fk_glossaire'), name='unique_itineraireDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='materiauxdanspoint',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_materiaux'), name='unique_materiauxDansPoint'),
        ),
        migrations.AddConstraint(
            model_name='metierdansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_metier', 'fk_glossaire'), name='unique_metierDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='pointdansglossaire',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_glossaire'), name='unique_pointDansGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_itineraire', 'positionDansItineraire'), name='unique_pointDansItineraire'),
        ),
    ]
