# Generated by Django 5.0.6 on 2024-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_lienrenumar_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metier',
            name='description',
            field=models.TextField(blank=True, help_text='Description du métier', null=True),
        ),
    ]
