# Generated by Django 5.0.3 on 2024-05-29 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_pointdansitineraire_unique_positiondansitineraire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursDeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itineraire', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
