# Generated by Django 5.0.3 on 2024-05-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_glossaire_options_alter_itineraire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraire',
            options={'verbose_name_plural': 'Itinéraires'},
        ),
        migrations.AlterModelOptions(
            name='pointdansitineraire',
            options={'ordering': ['positionDansItineraire']},
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='nom_arrivee',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='nom_depart',
        ),
        migrations.AddField(
            model_name='personnage',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnage',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointdansitineraire',
            name='fk_itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='map.itineraire'),
        ),
        migrations.AlterField(
            model_name='pointinteret',
            name='nom',
            field=models.CharField(help_text="Nom unique du point d'intérêt", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typepointinteret',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='glossaire',
            constraint=models.UniqueConstraint(fields=('mot',), name='unique_motGlossaire'),
        ),
        migrations.AddConstraint(
            model_name='personnage',
            constraint=models.UniqueConstraint(fields=('prenom', 'nom'), name='unique_nomPrenom'),
        ),
        migrations.AddConstraint(
            model_name='typepointinteret',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_typePoint'),
        ),
        migrations.AddConstraint(
            model_name='typequantite',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_typeQuantite'),
        ),
        migrations.AddConstraint(
            model_name='typevaleur',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_typeValeur'),
        ),
    ]
