# Generated by Django 5.0.6 on 2024-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_metier_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepointinteret',
            name='description',
            field=models.TextField(blank=True, help_text='Ajouter une description.', null=True),
        ),
    ]
