# Generated by Django 5.0.3 on 2024-05-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_itineraire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienRenumar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.URLField()),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materiauxdansitineraire',
            name='fk_typeQuantité',
        ),
        migrations.RemoveField(
            model_name='materiauxdansitineraire',
            name='fk_typeValeur',
        ),
        migrations.RemoveField(
            model_name='materiauxdansitineraire',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='materiauxdansitineraire',
            name='valeur',
        ),
        migrations.AddField(
            model_name='materiauxdansitineraire',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='LienRenumarItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire')),
                ('lien_renumar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.lienrenumar')),
            ],
        ),
        migrations.CreateModel(
            name='LienRenumarPointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien_renumar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.lienrenumar')),
                ('point_interet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pointinteret')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnageDansItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.itineraire')),
                ('fk_personnage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.personnage')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeQuantite',
        ),
        migrations.DeleteModel(
            name='TypeValeur',
        ),
    ]
