# Generated by Django 5.0.3 on 2024-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_coursdeau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursDeau',
        ),
    ]
