# Generated by Django 5.0.6 on 2024-06-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_typepointinteret_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MateriauxDansPoint',
        ),
    ]
