# Generated by Django 5.0.3 on 2024-05-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_itineraire_commentaire_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pointdansitineraire',
            name='unique_pointDansItineraire',
        ),
        migrations.AlterField(
            model_name='personnage',
            name='metiers_personnage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.metier'),
        ),
        migrations.AlterField(
            model_name='pointinteret',
            name='type_point_interet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.typepointinteret'),
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_pointInteret', 'fk_itineraire'), name='unique_pointDansItineraire'),
        ),
        migrations.AddConstraint(
            model_name='pointdansitineraire',
            constraint=models.UniqueConstraint(fields=('fk_itineraire', 'positionDansItineraire'), name='unique_positionDansItineraire'),
        ),
    ]
