# Generated by Django 5.0.3 on 2024-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_coursdeau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursdeau',
            name='id_coursDeau',
        ),
        migrations.AlterField(
            model_name='coursdeau',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
