# Generated by Django 5.0.3 on 2024-05-29 18:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_remove_coursdeau_id_coursdeau_alter_coursdeau_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('cdentitehy', models.CharField(max_length=255)),
                ('nomentiteh', models.CharField(max_length=255)),
                ('candidat', models.CharField(max_length=255)),
                ('classe', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='CoursDeau',
        ),
    ]
