# Generated by Django 5.0.3 on 2024-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_loiremodel_delete_coursdeau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loiremodel',
            name='candidat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
